// <auto-generated />
using System;
using AISportCoach.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AISportCoach.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AISportCoach.Domain.Entities.CoachingReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NtrpConfidence")
                        .HasColumnType("text");

                    b.Property<double?>("NtrpRating")
                        .HasColumnType("double precision");

                    b.Property<string>("NtrpRatingJustification")
                        .HasColumnType("text");

                    b.Property<double?>("NtrpRatingMax")
                        .HasColumnType("double precision");

                    b.Property<double?>("NtrpRatingMin")
                        .HasColumnType("double precision");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerSkillLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VideoUploadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VideoUploadId");

                    b.ToTable("CoachingReports");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.ImprovementRecommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachingReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.PrimitiveCollection<string>("DrillSuggestions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("TargetStroke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CoachingReportId");

                    b.ToTable("ImprovementRecommendations");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.NtrpEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoachingReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("NtrpIndicator")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<double>("SupportedLevel")
                        .HasColumnType("double precision");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CoachingReportId");

                    b.ToTable("NtrpEvidenceItems");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.TechniqueObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyPart")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CoachingReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FrameTimestamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Stroke")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoachingReportId");

                    b.ToTable("TechniqueObservations");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.VideoUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("GeminiFileUri")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("VideoUploads");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.CoachingReport", b =>
                {
                    b.HasOne("AISportCoach.Domain.Entities.VideoUpload", "VideoUpload")
                        .WithMany()
                        .HasForeignKey("VideoUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VideoUpload");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.ImprovementRecommendation", b =>
                {
                    b.HasOne("AISportCoach.Domain.Entities.CoachingReport", "CoachingReport")
                        .WithMany("Recommendations")
                        .HasForeignKey("CoachingReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoachingReport");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.NtrpEvidence", b =>
                {
                    b.HasOne("AISportCoach.Domain.Entities.CoachingReport", "CoachingReport")
                        .WithMany("NtrpEvidence")
                        .HasForeignKey("CoachingReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoachingReport");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.TechniqueObservation", b =>
                {
                    b.HasOne("AISportCoach.Domain.Entities.CoachingReport", "CoachingReport")
                        .WithMany("Observations")
                        .HasForeignKey("CoachingReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoachingReport");
                });

            modelBuilder.Entity("AISportCoach.Domain.Entities.CoachingReport", b =>
                {
                    b.Navigation("NtrpEvidence");

                    b.Navigation("Observations");

                    b.Navigation("Recommendations");
                });
#pragma warning restore 612, 618
        }
    }
}
